@startuml Button FSM Diagram
hide empty description

[*]--> IDLE
IDLE --> IDLE : GPIO = last_state
IDLE --> DEBOUNCE : GPIO != last_state \n----\n[start t_d]

DEBOUNCE --> DEBOUNCE : t_d < 30
DEBOUNCE --> IDLE : GPIO = last_state\nt_d >= 30
DEBOUNCE --> IDLE : GPIO != last_state\nt_d >= 30\n----\n\[last_state = GPIO]\n[current_state = GPIO]


@enduml